model_params:
  common_params:
    num_kp: 10
    num_channels: 3
    estimate_jacobian: True
  kp_detector_params:
     temperature: 0.1
     block_expansion: 32
     max_features: 1024
     scale_factor: 0.25
     num_blocks: 5
     adain_size: 7
     single_jacobian_map: False
     pad: 0
  generator_params:
    block_expansion: 64
    max_features: 512
    num_down_blocks: 2
    num_bottleneck_blocks: 6
    estimate_occlusion_map: True
    dense_motion_params:
      block_expansion: 64
      max_features: 1024
      num_blocks: 5
      scale_factor: 0.25


train_params:
  scales: [1, 0.5, 0.25, 0.125]
  emotion_temperature: 2
  learning_rate: 0.00003
  transform_params:
    sigma_affine: 0.05
    sigma_tps: 0.005
    points_tps: 5
  loss_weights:
    emotion_vectors: 0.1
    kp_location: 1
    perceptual: [0.025, 0.025, 0.025, 0.025, 0.025]
    equivariance_value: 0.1
    equivariance_jacobian: 0
